name: Hello World CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hello.py
        run: python hello.py

      - name: Run tests (pytest)
        run: pytest -q --maxfail=1 --junitxml=report.xml

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deployment (placeholder)
        run: |
          echo "✅ Deployment step running after successful build"
          echo "This is where you'd run rsync/ssh/docker push/gh-pages publish etc."
